version: '3.8'

services:
    postgres:
        image: postgres:17
        restart: unless-stopped
        container_name: history-sidepanel-db
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DATABASE}
            POSTGRES_HOST: postgres
        networks:
            - main-network
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        volumes:
            - /var/lib/postgresql/data
    
    api:
        container_name: history-sidepanel-api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        networks:
            - main-network
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DATABASE: ${POSTGRES_DATABASE}
networks:
    main-network: 
        driver: bridge
